name: Publish

on:
  workflow_dispatch:

jobs:
  publish_api:
    name: Publish jdave-api
    runs-on: ubuntu-latest
    environment: maven-central-release
    steps:
      - uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish to Maven Central
        env:
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.MAVENCENTRAL_TOKEN }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
        run: |
          ./gradlew api:publish api:jreleaserDeploy

  publis_native:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux
            runner: ubuntu-latest
          - target: aarch64-unknown-linux
            runner: ubuntu-latest
            skip-test: true
          - target: x86_64-pc-windows-msvc
            runner: windows-latest
          - target: darwin
            runner: macos-latest

    name: Publish Natives (${{ matrix.target }})
    runs-on: ${{ matrix.runner }}
    environment: maven-central-release
    steps:
      - uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish to Maven Central
        env:
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.MAVENCENTRAL_TOKEN }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
        run: |
          ./gradlew native:publish native:jreleaserDeploy -Ptarget=${{ matrix.target }} -x test
